<?php

namespace Database\Factories;

use App\Enums\PlanType;
use App\Models\Partner;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Plan>
 */
class PlanFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => \App\Models\User::factory(),
            'partner_id' => null,
            'name' => fake()->words(2, true).' Plan',
            'description' => fake()->sentence(),
            'is_active' => fake()->boolean(),
            'is_auto_generated' => false,
            'type' => PlanType::Routine,
            'duration_weeks' => null,
        ];
    }

    /**
     * Indicate that the plan is a program.
     */
    public function program(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => PlanType::Program,
            'duration_weeks' => fake()->numberBetween(4, 12),
        ]);
    }

    /**
     * Indicate that the plan is a partner library plan.
     */
    public function partnerLibrary(Partner $partner): static
    {
        return $this->state(fn (array $attributes) => [
            'partner_id' => $partner->id,
            'user_id' => null,
            'type' => PlanType::Program,
            'duration_weeks' => fake()->numberBetween(4, 12),
        ]);
    }

    /**
     * Indicate that the plan is a partner browsable routine.
     */
    public function partnerRoutine(Partner $partner): static
    {
        return $this->state(fn (array $attributes) => [
            'partner_id' => $partner->id,
            'user_id' => null,
            'type' => PlanType::Routine,
            'is_active' => true,
        ]);
    }

    /**
     * Indicate that the plan was auto-generated from the user's profile.
     */
    public function autoGenerated(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_auto_generated' => true,
        ]);
    }
}
