<?php

namespace App\Models;

use App\Enums\PlanType;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Plan extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'partner_id',
        'name',
        'description',
        'cover_image',
        'is_active',
        'is_auto_generated',
        'type',
        'duration_weeks',
    ];

    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'is_auto_generated' => 'boolean',
            'type' => PlanType::class,
        ];
    }

    /**
     * Relationship: Plan belongs to User
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Relationship: Plan belongs to Partner
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /**
     * Relationship: Plan has many WorkoutTemplates
     */
    public function workoutTemplates(): HasMany
    {
        return $this->hasMany(WorkoutTemplate::class);
    }

    /**
     * Check if this plan is a program
     */
    public function isProgram(): bool
    {
        return $this->type === PlanType::Program;
    }

    /**
     * Check if this plan is a routine
     */
    public function isRoutine(): bool
    {
        return $this->type === PlanType::Routine;
    }

    /**
     * Check if this is a partner library plan
     */
    public function isPartnerLibraryPlan(): bool
    {
        return $this->partner_id !== null && $this->user_id === null;
    }

    /**
     * Check if this plan is partner-provided (library or browsable routine)
     */
    public function isPartnerProvided(): bool
    {
        return $this->partner_id !== null && $this->user_id === null;
    }

    /**
     * Scope: Filter plans for a specific partner (library plans)
     */
    public function scopeForPartner(Builder $query, int $partnerId): Builder
    {
        return $query->where('partner_id', $partnerId)->whereNull('user_id');
    }

    /**
     * Scope: Filter plans for a specific user
     */
    public function scopeForUser(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Scope: auto-generated user plans (e.g. onboarding / regenerate).
     */
    public function scopeAutoGenerated(Builder $query): Builder
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Whether this plan was auto-generated from the user's profile.
     */
    public function isAutoGenerated(): bool
    {
        return (bool) $this->is_auto_generated;
    }
}
